### ISSUE TITLE
更新数据库不及时导致无法查看Rating

### ISSUE THREAD

**Issue by Pr0pHesyer** [PaperPig/MaimaiData#10]
在数据库较旧的情况下，无法登录查分，应用会退出至上一个界面甚至停止运行。
应该设置fallback方法，提示用户需要升级数据库或等待数据库更新。

**Comment by PaperPig** [comment]
最近比较忙，这个问题已经在修复了，晚点会提交更新

**Comment by PaperPig** [comment]
已修复
