### ISSUE TITLE
查分器保存图片功能失效

### ISSUE THREAD

**Issue by Sucareto** [PaperPig/MaimaiData#13]
具体现象：
点击 `Rating相关`->`查分`->`保存图片` 按钮后，加载 2 秒后退回 `Rating相关` 界面，没有生成图片，也未出现获取权限申请或提示信息。

测试设备：
OnePlus 7 Pro，Oxygen OS，Android 11
[Windows Subsystem for Android](https://learn.microsoft.com/zh-cn/windows/android/wsa/)，Android 13

**Comment by PaperPig** [comment]
b15和b25的歌曲封面在列表中都正常显示出来了吗

**Comment by Sucareto** [comment]
的确是有歌曲封面没有显示出来。
发现有某些歌曲的封面无法加载，比如 `町かどタンジェント` ，重启应用或点进这首歌的详情也无法加载。

**Comment by Sucareto** [comment]
稍微看了下源码，封面的来源似乎是 `IMAGE_BASE_URL` 定义的日服官网？上面提到的 `町かどタンジェント` 在日服已经被删除，有可能图片没了。封面改成从国服或者查分器那边获取怎么样？
如果能添加一个全封面下载功能或许不错...

**Comment by PaperPig** [comment]
查看了数据确实是少了该曲的曲封，之后更新会加上找不到图片的处理
