### ISSUE TITLE
Link(CoF) 曲绘消失，点进去崩溃

### ISSUE THREAD

**Issue by xian2xian2** [PaperPig/MaimaiData#16]
![1000045123](https://github.com/PaperPig/MaimaiData/assets/12865009/af5af930-0edd-4785-a2a3-3e1a3ec03e68)

一加8T，氧OS 13，Android 13
Maimai Data 2.3.0
已登录查分器且有分数数据
感觉类似 #13 ，水鱼加了 (CoF) 后缀而日服官网没有，然后找不到图？

**Comment by PaperPig** [comment]
这个曲名没对应上官网的数据
晚点会重发一下修复后的曲目资源包
