### ISSUE TITLE
"等级表进度"中选择LEVEL 7+显示的是LEVEL 8+的内容

### ISSUE THREAD

**Issue by yhFresca** [PaperPig/MaimaiData#21]
![1e9e0afc7a271ff72430b4be6749c684_720](https://github.com/user-attachments/assets/54d20681-1ec7-4a70-b34c-404f078704c5)

测试设备：
vivo X90，OriginOS 3，Android 13

**Comment by PaperPig** [comment]
手滑写成8+了....下个版本会修复
