### ISSUE TITLE
DX谱与标谱的相同难度显示相同达成状态

### ISSUE THREAD

**Issue by Pr0pHesyer** [PaperPig/MaimaiData#9]
在具有dx谱和标谱的歌曲的相同难度中显示的达成状态与完成率是相同的。
而它们实际上是不同的。
我未打过标准紫月に叢雲華に風，但是它显示了dx紫的完成状态与分数

**Comment by PaperPig** [comment]
好的 之前写的时候没有检查 晚点会看一下这个问题

**Comment by Pr0pHesyer** [comment]
> 好的 之前写的时候没有检查 晚点会看一下这个问题

已提交PR
